Repository django-tutorial-dev/Opensource-tutorials, pull requests merged in 2024-10, with the labels that each got.

#7 Added new contents
  file handling and IO/main.html
  file handling and IO/styles.css
Labels: hacktoberfest-accepeted

#5 Added content for tutorial
  main.html
  styles.css
Labels: pending

#4 Create Part 2 - Views.html
  Views/main.html
  demo tutorial/Part 2 - Views.html
  demo tutorial/part 2: Views
Labels: invalid
